language: rust
sudo: false
rust:
- stable
- beta
- nightly
script:
- (cd ogg && cargo build && cargo test --verbose)
- (cd ogg_clock && cargo build && cargo test --verbose)
- (cd ireul_interface && cargo build && cargo test --verbose)
- (cd ireul-client && cargo build && cargo test --verbose)
- cargo test --verbose
